# Requires variables
#   * DO_TOKEN
#	* DOCKER_USER
#	* DOCKER_PASS
#	* DEPLOY_NODE

defaults: &DEFAULT
  working_directory: ~/app
  docker:
    - image: docker:18.06.0-ce-git

version: 2
jobs:
  build:
    <<: *DEFAULT
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install dependencies
          command: |
            echo "No dependencies"
      - run:
          name: Build the Builder
          command: |
            docker build -t c-os-build-ci -f Dockerfile.ci.build .
      - run:
          name: Build the OS
          command: |
            docker run -itd --name c-os-ci c-os-build-ci sh
            docker exec c-os-ci scons
            docker cp c-os-ci:/app/build .
            docker cp c-os-ci:/app/pcjs/c-os.json ./pcjs/
            docker stop c-os-ci
            docker rm c-os-ci
      - run:
          name: Build application Docker image
          command: |
            docker build -t lapinlabs/c-os .
      # Note: we don't push here, we wait for tests to pass and push in the deploy job

  test:
    <<: *DEFAULT
    steps:
      - run:
          name: Do Test
          command: echo no tests

  build_and_deploy:
    <<: *DEFAULT
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            echo "No dependencies"
      - run:
          name: Build the Builder
          command: |
            docker build -t c-os-build-ci -f Dockerfile.ci.build .
      - run:
          name: Build the OS
          command: |
            docker run -itd --name c-os-ci c-os-build-ci sh
            docker exec c-os-ci scons
            docker cp c-os-ci:/app/build .
            docker cp c-os-ci:/app/pcjs/c-os.json ./pcjs/
            docker stop c-os-ci
            docker rm c-os-ci
      - run:
          name: Build application Docker image
          command: |
            docker build -t lapinlabs/c-os .
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag lapinlabs/c-os lapinlabs/c-os:${CIRCLE_BRANCH//\//-}-${CIRCLE_BUILD_NUM}
            docker push lapinlabs/c-os:${CIRCLE_BRANCH//\//-}-${CIRCLE_BUILD_NUM}
            docker push lapinlabs/c-os:latest
      - run:
          name: Remotely deploy to droplet
          command: |
            apk add --update curl curl-dev jq
            export IP=`curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DO_TOKEN" "https://api.digitalocean.com/v2/droplets/" | jq ".droplets[] | select(.name == \"$DEPLOY_NODE\") | .networks.v4[0].ip_address"`
            export IP=`echo $IP | sed -e 's/^"//' -e 's/"$//'`
            echo "Deploying to $DEPLOY_NODE [$IP]"
            ssh -o StrictHostKeyChecking=no root@${IP} "service container-c-os redeploy"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test:
          context: deployment
      - build:
          context: deployment
      - build_and_deploy:
          context: deployment
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - ci
                - master
